(() => {
  'use strict';
  const VERSION='0.16';
  const Parser=window.NeuroProfileTextParser;
  const App=window.NeuroProfileAppController;
  let lastResult=null;
  let refreshScheduled=false;

  function buildPanel(){
    const panel=document.createElement('details');
    panel.className='np013-parser';
    panel.id='np013-text-parser';
    panel.innerHTML=`
      <summary>Paste score table</summary>
      <div class="np013-parser-body">
        <div class="np013-parser-target">
          <div class="field-group"><label for="np013-parser-target">Load into assessment</label><select class="select-input" id="np013-parser-target"></select></div>
          <div class="field-group"><label for="np013-parser-source-name">Source label</label><input class="text-input" id="np013-parser-source-name" maxlength="60" value="Pasted score table" autocomplete="off" spellcheck="false"></div>
        </div>
        <div class="field-group"><label for="np013-parser-input">Score table text</label><textarea class="text-input" id="np013-parser-input" rows="9" maxlength="750000" autocomplete="off" autocapitalize="off" spellcheck="false" placeholder="Cognitive Domain    Test Name    T-score\nProcessing Speed    Coding       52\nAttention           Digit Span   44"></textarea></div>
        <details class="np013-parser-options"><summary>Parser options</summary><div class="np013-parser-option-grid">
          <div class="field-group"><label for="np013-parser-orientation">Table orientation</label><select class="select-input" id="np013-parser-orientation"><option value="auto">Auto-detect</option><option value="rows">Tests in rows</option><option value="columns">Tests in columns</option></select></div>
          <div class="field-group"><label for="np013-parser-preferred-metric">Preferred score type</label><select class="select-input" id="np013-parser-preferred-metric"><option value="">Auto</option><option value="T">T-score</option><option value="Z">z-score</option><option value="Standard">Standard score</option><option value="Scaled">Scaled score</option><option value="Percentile">Percentile rank</option></select></div>
          <div class="field-group"><label for="np013-parser-default-metric">Generic Score column</label><select class="select-input" id="np013-parser-default-metric"><option value="">Auto-detect metric</option><option value="T">Treat as T-score</option><option value="Z">Treat as z-score</option><option value="Standard">Treat as standard score</option><option value="Scaled">Treat as scaled score</option><option value="Percentile">Treat as percentile rank</option></select></div>
          <label class="np013-parser-check"><input id="np013-parser-infer-domains" type="checkbox" checked>Infer missing domains from test names</label>
        </div></details>
        <div class="np013-parser-actions"><button class="btn btn-primary" id="np013-parser-parse" type="button">Parse table</button><button class="btn" id="np013-parser-clear" type="button">Clear text</button></div>
        <div class="np013-parser-status" id="np013-parser-status" role="status" aria-live="polite"></div>
        <div class="np013-parser-results" id="np013-parser-results" hidden>
          <div class="np013-parser-summary" id="np013-parser-summary"></div><ul class="np013-parser-warnings" id="np013-parser-warnings" hidden></ul>
          <div class="np013-parser-preview-wrap"><table class="np013-parser-preview"><caption class="sr-only">Preview of parsed test scores</caption><thead><tr><th scope="col">Domain</th><th scope="col">Test</th><th scope="col">Score</th><th scope="col">Metric</th><th scope="col">Detection</th></tr></thead><tbody id="np013-parser-preview-body"></tbody></table></div>
          <div class="np013-parser-load-row"><span class="np013-parser-load-note" id="np013-parser-load-note"></span><button class="btn btn-primary" id="np013-parser-load" type="button">Load parsed scores</button></div>
        </div>
      </div>`;
    return panel;
  }

  const byId=id=>document.getElementById(id);
  function getUi(){return{panel:byId('np013-text-parser'),target:byId('np013-parser-target'),sourceName:byId('np013-parser-source-name'),input:byId('np013-parser-input'),orientation:byId('np013-parser-orientation'),preferredMetric:byId('np013-parser-preferred-metric'),defaultMetric:byId('np013-parser-default-metric'),inferDomains:byId('np013-parser-infer-domains'),parse:byId('np013-parser-parse'),clearButton:byId('np013-parser-clear'),status:byId('np013-parser-status'),results:byId('np013-parser-results'),summary:byId('np013-parser-summary'),warnings:byId('np013-parser-warnings'),previewBody:byId('np013-parser-preview-body'),loadNote:byId('np013-parser-load-note'),load:byId('np013-parser-load')}}
  function setStatus(ui,text,type=''){ui.status.textContent=text||'';ui.status.classList.toggle('is-error',type==='error');ui.status.classList.toggle('is-success',type==='success')}
  function assessmentLabel(a){return `${a.label}${a.isCurrent?' (Current)':''}`}
  function refreshAssessmentOptions(ui){const assessments=App.getAssessments();const previous=ui.target.value;const active=App.getActiveAssessmentId();ui.target.replaceChildren();assessments.forEach(a=>{const o=document.createElement('option');o.value=a.id;o.textContent=assessmentLabel(a);ui.target.appendChild(o)});ui.target.value=assessments.some(a=>a.id===previous)?previous:active;updateLoadText(ui)}
  function updateLoadText(ui){const selected=App.getAssessments().find(a=>a.id===ui.target.value);const label=selected?selected.label:'selected assessment';ui.load.textContent=`Load into ${label}`;ui.loadNote.textContent=selected&&selected.hasData?'Loading replaces the score data in this assessment.':''}
  function clearResults(ui,text=''){lastResult=null;ui.results.hidden=true;ui.previewBody.replaceChildren();ui.warnings.replaceChildren();ui.warnings.hidden=true;ui.load.disabled=true;setStatus(ui,text)}
  function parserOptions(ui){return{orientation:ui.orientation.value,preferredMetric:ui.preferredMetric.value||null,defaultMetric:ui.defaultMetric.value||null,inferDomains:ui.inferDomains.checked}}
  function detectionText(r){const p=[r.domainSource==='inferred'?'Domain inferred':r.domainSource==='unassigned'?'Unassigned':'Domain supplied'];if(!r.include)p.push('Excluded');return p.join(' · ')}
  function renderPreview(ui,result){const s=result.summary;ui.summary.replaceChildren();const strong=document.createElement('strong');strong.textContent=`${s.included} included score${s.included===1?'':'s'} across ${s.domains} domain${s.domains===1?'':'s'}.`;ui.summary.append(strong,document.createTextNode(` ${result.diagnostics.layout}; ${result.diagnostics.orientation==='columns'?'tests in columns':'tests in rows'}.`));if(s.inferredDomains)ui.summary.append(document.createTextNode(` ${s.inferredDomains} domain assignment${s.inferredDomains===1?'':'s'} inferred.`));ui.warnings.replaceChildren();result.warnings.slice(0,5).forEach(w=>{const li=document.createElement('li');li.textContent=w;ui.warnings.appendChild(li)});if(result.warnings.length>5){const li=document.createElement('li');li.textContent=`${result.warnings.length-5} additional parser warning${result.warnings.length-5===1?'':'s'}.`;ui.warnings.appendChild(li)}ui.warnings.hidden=!result.warnings.length;ui.previewBody.replaceChildren();result.records.slice(0,15).forEach(r=>{const tr=document.createElement('tr');if(!r.include)tr.className='np013-parser-excluded';[r.domain,r.measure,r.score,r.metric,detectionText(r)].forEach((v,i)=>{const td=document.createElement('td');td.textContent=String(v??'');if(i===4)td.className='np013-parser-source';tr.appendChild(td)});ui.previewBody.appendChild(tr)});if(result.records.length>15){const tr=document.createElement('tr');const td=document.createElement('td');td.colSpan=5;td.className='np013-parser-source';td.textContent=`${result.records.length-15} additional parsed score row${result.records.length-15===1?'':'s'}.`;tr.appendChild(td);ui.previewBody.appendChild(tr)}ui.load.disabled=s.included<1;ui.results.hidden=false;updateLoadText(ui)}
  function parseInput(ui){setStatus(ui,'Parsing score table…');try{lastResult=Parser.parse(ui.input.value,parserOptions(ui));renderPreview(ui,lastResult);setStatus(ui,'Review the parsed rows before loading them.','success')}catch(e){clearResults(ui);setStatus(ui,e.message||'The pasted score table could not be parsed.','error')}}
  function loadParsed(ui){if(!lastResult||lastResult.summary.included<1)return;const assessmentId=ui.target.value||App.getActiveAssessmentId();const selected=App.getAssessments().find(a=>a.id===assessmentId);if(App.assessmentHasData(assessmentId)&&!window.confirm(`Replace the score data currently loaded in ${selected?selected.label:'the selected assessment'}?`))return;try{App.setActiveAssessment(assessmentId);const imported=App.importCanonicalRows(lastResult.rows,{assessmentId,sourceName:ui.sourceName.value.trim()||'Pasted score table',characterCount:ui.input.value.length});refreshAssessmentOptions(ui);setStatus(ui,`${imported.scores} score${imported.scores===1?'':'s'} loaded into ${imported.label}.`,'success')}catch(e){setStatus(ui,e.message||'The parsed scores could not be loaded.','error')}}
  function scheduleRefresh(ui){if(refreshScheduled)return;refreshScheduled=true;requestAnimationFrame(()=>{refreshScheduled=false;refreshAssessmentOptions(ui)})}
  function initialize(){const dropZone=byId('dropZone');if(!dropZone||!Parser||!App||byId('np013-text-parser'))return;dropZone.insertAdjacentElement('afterend',buildPanel());const ui=getUi();refreshAssessmentOptions(ui);ui.load.disabled=true;ui.parse.addEventListener('click',()=>parseInput(ui));ui.clearButton.addEventListener('click',()=>{ui.input.value='';clearResults(ui);ui.input.focus()});ui.load.addEventListener('click',()=>loadParsed(ui));ui.target.addEventListener('change',()=>{App.setActiveAssessment(ui.target.value);updateLoadText(ui)});ui.input.addEventListener('input',()=>{if(lastResult)clearResults(ui,'Table changed. Parse again to update the preview.')});[ui.orientation,ui.preferredMetric,ui.defaultMetric,ui.inferDomains].forEach(c=>c.addEventListener('change',()=>{if(lastResult)clearResults(ui,'Parser options changed. Parse again to update the preview.')}));ui.input.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();parseInput(ui)}});const observer=new MutationObserver(()=>scheduleRefresh(ui));const list=byId('assessmentList');const active=byId('activeAssessmentName');if(list)observer.observe(list,{childList:true,subtree:true,characterData:true});if(active)observer.observe(active,{childList:true,subtree:true,characterData:true});document.addEventListener('change',e=>{if(e.target&&['singleAssessmentMode','multipleAssessmentsMode','editAssessmentSelect'].includes(e.target.id))scheduleRefresh(ui)});window.NeuroProfileTextParserController=Object.freeze({version:VERSION,parseCurrent(){parseInput(ui);return lastResult},getLastResult(){return lastResult},loadCurrent(){loadParsed(ui)},refreshAssessments(){refreshAssessmentOptions(ui)},clear(){ui.input.value='';clearResults(ui)}})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initialize,{once:true});else initialize();
})();
